#开发环境配置文件
server:
  port: 8443
  ssl:
    key-store: classpath:cert/yogurtcat.keystore
    key-store-password: 1qaz@WSX3edc
    key-password: 1qaz@WSX3edc
  tomcat:
    basedir: yogurtcat-server-system
    accesslog:
      enabled: true
      pattern: "%t %a '%r' %s (%D ms)"
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    url: jdbc:h2:mem:yogurtcat;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: root
  h2:
    console:
      enabled: true
  data:
    elasticsearch:
        repositories:
            enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    host: 132.232.54.102
    port: 5672
    username: admin
    password: secret
    template: 
        retry:
            enabled: true
            initial-interval: 2s
logging:
  level:
    root: info
  file:
    path: yogurtcat-server-system/logs/
    name: yogurtcat-server-system.log
    
jwt:
  expiration: 720000000
  secret: test
